name: Connectivity Test

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  connectivity-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Test connectivity to key endpoints
      - name: Test connectivity to key endpoints
        run: |
          endpoints=(
            "archive.ubuntu.com"
            "security.ubuntu.com"
            "github.com"
            "api.github.com"
            "objects.githubusercontent.com"
            "releases.hashicorp.com"
            "deb.nodesource.com"
            "packages.microsoft.com"
            "login.microsoftonline.com"
            "management.azure.com"
            "sa01poc20099wh701.blob.core.windows.net"
          )

          for endpoint in "${endpoints[@]}"; do
            echo "Testing $endpoint..."
            if curl -s --head --request GET "http://$endpoint" | grep "200 OK" > /dev/null || \
               curl -s --head --request GET "https://$endpoint" | grep "200 OK" > /dev/null; then
              echo "$endpoint: SUCCESS"
            else
              echo "$endpoint: FAILURE"
            fi
          done
