name: Test Firewall opening to login.microsoftonline.com

on:
  push

jobs:
  test-connectivity:
    #runs-on: sandbox-azure-runner
    runs-on: shell-runner-set-poc-org
    steps:
      - name: Test connectivity to login.microsoftonline.com
        id: test_connection
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://login.microsoftonline.com)
          echo "HTTP Status Code: $STATUS"
          if [ "$STATUS" -eq 200 ]; then
            echo "connectivity_status=success" >> "$GITHUB_OUTPUT"
          else
            echo "connectivity_status=failure (HTTP $STATUS)" >> "$GITHUB_OUTPUT"
          fi

      - name: Output connectivity status
        run: |
          echo "Connectivity Test Result: ${{ steps.test_connection.outputs.connectivity_status }}"
