
name: AZ CLI Login with OpenID Connect

on: 
  push

jobs:
  test:
    runs-on: 
      group: sandbox-azure-runner-group  # Use self-hosted runner group
    environment: test  # GitHub environment (can be used for approvals/secrets)

    permissions:
      id-token: write  # Required for OIDC authentication with Azure
      contents: read   # Allows reading repo contents

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate to Azure using federated credentials (OIDC)
      - name: Azure CLI Login
        uses: azure/login@v1.4.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 3: Show Azure account details
      - name: Show Az Account
        run: az account show
