name: Terraform Deployment (Test)

on:
  push

jobs:
  terraform:
    name: Terraform Apply (Test)
    runs-on: ubuntu-latest
    environment: test

    permissions:
      id-token: write
      contents: read

    env:
      TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure using Federated Credentials
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: false

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Import Resource Group (if not already imported)
        run: |
          cd terraform
          terraform state list | grep azurerm_resource_group.rg || \
          terraform import azurerm_resource_group.rg /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-cummins-tf-lab2-wh701

      - name: Terraform Plan (Test Environment)
        run: |
          cd terraform
          terraform plan -var-file="test.tfvars" -out=tfplan

      - name: Terraform Apply (Test Environment)
        run: |
          cd terraform
          terraform apply -auto-approve tfplan
